### ISSUE TITLE
[每日信息流] 2024-07-08

### ISSUE THREAD

**Issue by Sakura-gkf** [Sakura-gkf/picker#437]
# 每日安全资讯（2024-07-08）

- SecWiki News
  - [ ] [SecWiki News 2024-07-07 Review](http://www.sec-wiki.com/?2024-07-07)
- Doonsec's feed
  - [ ] [2024年，还能报计算机专业吗？](https://mp.weixin.qq.com/s?__biz=Mzg2NDYwMDA1NA==&mid=2247539415&idx=1&sn=ca89501c6dc09a1e5bf4be61924f67b0)
  - [ ] [加入T00ls，与网络安全精英同行！](https://mp.weixin.qq.com/s?__biz=Mzg3NzYzODU5NQ==&mid=2247484672&idx=1&sn=8e5cd6196fcb8da9e6d3cad85f029941)
  - [ ] [从Scala Chain看新切入面](https://mp.weixin.qq.com/s?__biz=Mzg5MzE4MjAxMw==&mid=2247484249&idx=1&sn=b5218395ef7ad39634e61adf37bca163)
  - [ ] [秦安：俄卫星神奇解体，砸中美GPS和星链卫星，美俄已经直接冲突](https://mp.weixin.qq.com/s?__biz=MzA5MDg1MDUyMA==&mid=2650471009&idx=1&sn=e2e7d0cc12577d1378284030edf8dac0)
  - [ ] [王常胜：引敌为友、化友为敌，会将国家推向孤立和危险境地](https://mp.weixin.qq.com/s?__biz=MzA5MDg1MDUyMA==&mid=2650471009&idx=2&sn=78fa15d61f1178959be2ed7fd52978ca)
  - [ ] [牟林：是和平计划，还是最后通牒？](https://mp.weixin.qq.com/s?__biz=MzA5MDg1MDUyMA==&mid=2650471009&idx=3&sn=11c2c661c461a21665c38181ded3b83c)
  - [ ] [《诗词游记》第340期：卦台可触天](https://mp.weixin.qq.com/s?__biz=MzA5MDg1MDUyMA==&mid=2650471009&idx=4&sn=89f398417fb8424ac1249501a4d023b5)
  - [ ] [《诗词游记》第341期：昨夜麦积雨](https://mp.weixin.qq.com/s?__biz=MzA5MDg1MDUyMA==&mid=2650471009&idx=5&sn=18f261689b598dcf808b37295c9594c1)
  - [ ] [逆向学习汇编篇 -- 硬件断点的概念、特点及其在调试过程中的关键应用](https://mp.weixin.qq.com/s?__biz=MzA4MzgzNTU5MA==&mid=2652035424&idx=1&sn=78ae185fd4dfe3e4d1477d6bbdbe5c1b)
  - [ ] [逆向学习汇编篇 -- 如何处理硬件和软件断点](https://mp.weixin.qq.com/s?__biz=MzA4MzgzNTU5MA==&mid=2652035424&idx=2&sn=540f0a238f6252738743958108269201)
  - [ ] [Spring Boot Actuator未授权内存分析方法](https://mp.weixin.qq.com/s?__biz=MzIzMTIzNTM0MA==&mid=2247495128&idx=1&sn=8348750168970a4f8027592d98724266)
  - [ ] [网络安全学习资料 -- 文件包含+命令执行](https://mp.weixin.qq.com/s?__biz=MzU3NzY3MzYzMw==&mid=2247497814&idx=1&sn=a2d74b82fc5b69275c080e78ee6488ea)
  - [ ] [AI视频项目：老旧照片转视频](https://mp.weixin.qq.com/s?__biz=MzU3NzY3MzYzMw==&mid=2247497814&idx=2&sn=5aa864541f0f513b6c64e73005979c97)
  - [ ] [威胁情报周报（7.1~7.7）](https://mp.weixin.qq.com/s?__biz=Mzg5MTc3ODY4Mw==&mid=2247506241&idx=1&sn=a76fc42339b088ea15f3fdd6553ea83d)
  - [ ] [2024HW必修漏洞集合（PDF下载）](https://mp.weixin.qq.com/s?__biz=MzI4MDQ5MjY1Mg==&mid=2247513407&idx=1&sn=2fb44ef74d40e4db0079da01e5d2ab34)
  - [ ] [红队实战教学 -- Metasploit Framework的使用](https://mp.weixin.qq.com/s?__biz=MzI4MDQ5MjY1Mg==&mid=2247513407&idx=2&sn=595655014bdc7119d516b0616d2fa895)
  - [ ] [SecMet#5期  智能代码审计：机遇、挑战与解决方案](https://mp.weixin.qq.com/s?__biz=MzU5MTM5MTQ2MA==&mid=2247491039&idx=1&sn=1c7aad358d4c0cc2f595b0beafc92b1b)
  - [ ] [《hw之荣耀黑客》1](https://mp.weixin.qq.com/s?__biz=Mzg4NzgzMjUzOA==&mid=2247484082&idx=1&sn=2de59cccdd785324c6abb5b5afae7d9a)
  - [ ] [汽车区块链市场：驶向41亿美元的未来](https://mp.weixin.qq.com/s?__biz=MzIxODg1OTkzMg==&mid=2247487266&idx=1&sn=2ceeb31c424b4625a2c48fa762014935)
  - [ ] [铤而走险-诈骗站点溯源](https://mp.weixin.qq.com/s?__biz=MzkyNDQ5NDM3OA==&mid=2247483934&idx=1&sn=c1da20d1cfd0c61a427b2a50e580ad68)
  - [ ] [RIP-2的增强特性，RIP-2比RIP-1强在哪里？](https://mp.weixin.qq.com/s?__biz=MzUyNTExOTY1Nw==&mid=2247524531&idx=1&sn=778162d5a73167d17b999e44c97577e1)
  - [ ] [红队快速打点漏洞检测工具 | POC-bomber](https://mp.weixin.qq.com/s?__biz=MzUyMTA0MjQ4NA==&mid=2247550333&idx=1&sn=4810139bf7b0df2581c68ec244122761)
  - [ ] [红队技巧 -- 自启持久化](https://mp.weixin.qq.com/s?__biz=MzUyMTA0MjQ4NA==&mid=2247550333&idx=2&sn=0a444160a5d814872fbeec51edfbfb2e)
  - [ ] [linux高级usb安全开发与源码分析视频更新到165节啦](https://mp.weixin.qq.com/s?__biz=MzkwOTE5MDY5NA==&mid=2247497430&idx=1&sn=b851072c6c2ff435199a78f460af6058)
  - [ ] [东半球顶级赛事开幕！“矩阵杯”网络安全大赛见证顶尖战队巅峰对决](https://mp.weixin.qq.com/s?__biz=MzkyNjQ0NTQ2NA==&mid=2247493590&idx=1&sn=9630a6e4a036fd9847252dc73f899bae)
  - [ ] [【资讯】人工智能全球治理上海宣言（全文）](https://mp.weixin.qq.com/s?__biz=MzU1NDY3NDgwMQ==&mid=2247543199&idx=1&sn=7cacf1102fc510315b4f5177d45bad63)
  - [ ] [【资讯】湖南省政府办公厅印发《湖南省专利转化运用专项行动实施方案》](https://mp.weixin.qq.com/s?__biz=MzU1NDY3NDgwMQ==&mid=2247543199&idx=2&sn=9b9ac6b17c4485005831e70c5b714a0b)
  - [ ] [【资讯】内蒙古自治区工信厅印发《2024年度法治政府建设工作计划》](https://mp.weixin.qq.com/s?__biz=MzU1NDY3NDgwMQ==&mid=2247543199&idx=3&sn=8e3fe9621852de28ec764158ad9fcf29)
  - [ ] [一名间谍罪犯的狱中自白](https://mp.weixin.qq.com/s?__biz=MzkwMTMyMDQ3Mw==&mid=2247590490&idx=1&sn=bbd5db53705bf0655e9d705e02f54dfc)
  - [ ] [Remote Code Execution RCE漏洞详解](https://mp.weixin.qq.com/s?__biz=Mzg3MzUxNDQwNg==&mid=2247483770&idx=1&sn=d7a17b53977b2928d804cd2455868a4f)
  - [ ] [格密码学习笔记(十二)NTRU加密体系](https://mp.weixin.qq.com/s?__biz=MzUwOTc3MTQyNg==&mid=2247489066&idx=1&sn=cb7e588a1f14cb757a321fca0cdfa97d)
  - [ ] [6月，师傅们终于迈过了4W这道坎！](https://mp.weixin.qq.com/s?__biz=MzkwODM3NjIxOQ==&mid=2247500952&idx=1&sn=dbecf3cf108e8fd1d69671143bc83306)
  - [ ] [影响 300 万款苹果 iOS / macOS 应用，CocoaPods 平台漏洞披露](https://mp.weixin.qq.com/s?__biz=MzI0NzE4ODk1Mw==&mid=2652093147&idx=1&sn=384018a7aa07fbeb482872c5e48c05d7)
  - [ ] [新的 OpenSSH 漏洞可能导致 Linux 系统以 Root 身份进行 RCE](https://mp.weixin.qq.com/s?__biz=MzI0NzE4ODk1Mw==&mid=2652093147&idx=2&sn=d85f43bd86138d72636fb232958b4d88)
  - [ ] [洞见者：布热津斯基思想述评](https://mp.weixin.qq.com/s?__biz=MzI1OTExNDY1NQ==&mid=2651614009&idx=1&sn=c8d8a865ffab58301dd67b52dd9a07f1)
  - [ ] [某UI众人帮悬赏任务系统审计(0day)](https://mp.weixin.qq.com/s?__biz=Mzg4MTkwMTI5Mw==&mid=2247484634&idx=1&sn=f686460168fa48fb5978cd71a9788d27)
  - [ ] [开源堡垒机那么多，该如何选择？](https://mp.weixin.qq.com/s?__biz=MzIyMzIwNzAxMQ==&mid=2649459358&idx=1&sn=49048030c14260eb3a63ee4443df1251)
  - [ ] [产线终端桌面云用户最关心的十个问题！详解来了](https://mp.weixin.qq.com/s?__biz=MjM5MTAzNjYyMA==&mid=2650589024&idx=1&sn=42ca4c1bbc78da4d4395d17a419df114)
  - [ ] [知识星球 | 请问有收到网安上门检查的通知吗？网安新兴赛道厂商有哪些？](https://mp.weixin.qq.com/s?__biz=MzU5ODgzNTExOQ==&mid=2247624986&idx=1&sn=ad2e8ba558996bdd5c8b81cede9e357a)
  - [ ] [车联网安全入门之仿真一辆车的通信网络](https://mp.weixin.qq.com/s?__biz=MzIzOTc2OTAxMg==&mid=2247539970&idx=1&sn=3fffb0f6dc80cf93aaec4b66c9a8db06)
  - [ ] [『SDC 2024』创新议题等你来投！早鸟票抢购中](https://mp.weixin.qq.com/s?__biz=MjM5NTc2MDYxMw==&mid=2458562488&idx=1&sn=e5cc0a0dd4dff941866c4e034a783a13)
  - [ ] [VMP源码分析：反调试与绕过方法](https://mp.weixin.qq.com/s?__biz=MjM5NTc2MDYxMw==&mid=2458562488&idx=2&sn=fe5bd1498948137775db5f454bd5a6a2)
  - [ ] [实录来了！国新办举行“推动高质量发展”系列主题新闻发布会（工业和信息化部）](https://mp.weixin.qq.com/s?__biz=MzU1OTUxNTI1NA==&mid=2247589814&idx=1&sn=35440e8cb0c342d29962b6d5abe0c748)
  - [ ] [2024世界人工智能大会｜国内首份“大模型安全实践”报告发布](https://mp.weixin.qq.com/s?__biz=MjM5MzMwMDU5NQ==&mid=2649165383&idx=1&sn=b3594b73412a41a77398f24dcbf4e59a)
  - [ ] [2024世界人工智能大会闭幕，一文回顾AI界大咖都说了些啥？](https://mp.weixin.qq.com/s?__biz=MjM5MzMwMDU5NQ==&mid=2649165383&idx=2&sn=ad6bb15af383adfe3442892f99a8bf7e)
  - [ ] [【漏洞复现】亿赛通 电子文档安全管理系统 PolicyAjax Sql注入漏洞](https://mp.weixin.qq.com/s?__biz=MzkyMDUwOTU1MA==&mid=2247484382&idx=1&sn=535dad489a072dc1c878cb59c7641a15)
  - [ ] [服务排查脚本完善 | Windows 应急响应](https://mp.weixin.qq.com/s?__biz=MzU1NDkwMzAyMg==&mid=2247502017&idx=1&sn=9e3bd65ccd0aaa0e27004074d28ad6b4)
  - [ ] [生态合作伙伴招募](https://mp.weixin.qq.com/s?__biz=MzU1NDkwMzAyMg==&mid=2247502017&idx=2&sn=6ef35e68e3d332168ce2fbee1b5d814d)
  - [ ] [你真的会Webpack加密算法逆向吗？](https://mp.weixin.qq.com/s?__biz=MzkyNzQ1NjI4OA==&mid=2247484454&idx=1&sn=eb01f6b77779bb573930bf3b79529e6c)
  - [ ] [贵州省政务服务中心信息安全防护项目数据安全和云安全服务及密码改造子项的招标](https://mp.weixin.qq.com/s?__biz=MzIxMDIwODM2MA==&mid=2653930268&idx=1&sn=6a09ba60e28cccd43aa69a034cd31226)
  - [ ] [麒麟信安串通投标被禁止参加军队采购1年](https://mp.weixin.qq.com/s?__biz=MzIxMDIwODM2MA==&mid=2653930268&idx=2&sn=920df4b4b2064ae3c2764a837074a4e9)
  - [ ] [第一次的pentest show总结](https://mp.weixin.qq.com/s?__biz=MzkxNTU5NTI1Ng==&mid=2247485022&idx=1&sn=5ebf32c9cf4d4197996916ffe4166ff7)
  - [ ] [你用一栋办公楼怎么装得下我对世界的思考](https://mp.weixin.qq.com/s?__biz=MzkzMDM5NzIwMw==&mid=2247484502&idx=1&sn=9f675dfe5af38c52f7b3947a08293d7d)
  - [ ] [一图读懂数据安全分级分类规则](https://mp.weixin.qq.com/s?__biz=MzU2MDQ0NzkyMw==&mid=2247484830&idx=1&sn=d56bdaceef7fbb9993133d9de5e657b8)
  - [ ] [CCF-快手大模型探索者基金启动！诚邀申报五大前沿研究方向！](https://mp.weixin.qq.com/s?__biz=Mzg2NzU4MDM0MQ==&mid=2247487235&idx=1&sn=179c99622410731efc49ff33cbe4feba)
  - [ ] [2023年国内数字安全市场规模为973.7亿元，附2024中国数字安全产业年度报告](https://mp.weixin.qq.com/s?__biz=MzI3NjUzOTQ0NQ==&mid=2247512359&idx=1&sn=1e021d7e583ee7930e1676762ed5631d)
  - [ ] [到底哪个吊一点？](https://mp.weixin.qq.com/s?__biz=Mzk0NzQxNzY2OQ==&mid=2247486570&idx=1&sn=c4fc44367e5394be013513223189e5fd)
  - [ ] [l-l VV打油诗](https://mp.weixin.qq.com/s?__biz=MzI1OTUyMTI2MQ==&mid=2247484596&idx=1&sn=7da13faaf1ee78031e4c5b24596d2425)
  - [ ] [融合时间应用，信息化工作会变得与众不同！](https://mp.weixin.qq.com/s?__biz=MzA3OTg3Mjg3NA==&mid=2456976100&idx=1&sn=fe49763db817eca351a576a2e42a7be5)
  - [ ] [最新的Ghostscript漏洞困扰着专家，成为下一个重大漏洞的推动者](https://mp.weixin.qq.com/s?__biz=MzI5NTA0MTY2Mw==&mid=2247485415&idx=1&sn=52a693006c8ff941f0e24d88657f3746)
  - [ ] [ctftools-all-in-oneV3.5发布](https://mp.weixin.qq.com/s?__biz=MzI1NzUxOTUzMA==&mid=2247485410&idx=1&sn=24175bc2a9060d15d51c41f9f9cc07b6)
  - [ ] [CVE-2024-36401 远程代码执行 (RCE) 漏洞 绕过 waf poc](https://mp.weixin.qq.com/s?__biz=MzAxMjYyMzkwOA==&mid=2247510451&idx=1&sn=a8c582e83e35747d6fae99869fb987ec)
  - [ ] [发现适用于 Linux 的 TgRat 间谍软件：tgRat 的强大且先进的 2024 版本](https://mp.weixin.qq.com/s?__biz=MzAxMjYyMzkwOA==&mid=2247510451&idx=2&sn=b816d617f1829e45eeb4ceea43ab80f2)
  - [ ] [滥用 Cloud Kerberos Trust 从 Azure AD 获取域管理员权限](https://mp.weixin.qq.com/s?__biz=MzAxMjYyMzkwOA==&mid=2247510451&idx=3&sn=2929681f0bfbbc7edd339864486e247c)
  - [ ] [【车联网】大众高尔夫动力转向ECU破解（4）](https://mp.weixin.qq.com/s?__biz=Mzg4NTczMTMyMQ==&mid=2247486151&idx=1&sn=3c4af870b75a5c6dfb4e9386db53c007)
  - [ ] [某U验证平台任意文件写入](https://mp.weixin.qq.com/s?__biz=MzkwMzcwMDU5OA==&mid=2247483801&idx=1&sn=0a3e08433585f7be86d0860bb36725ca)
  - [ ] [【预警】windows本地提权0day漏洞在暗网售卖（未被证实，还处于第三方校验阶段）](https://mp.weixin.qq.com/s?__biz=MzkzNDIzNDUxOQ==&mid=2247486562&idx=1&sn=0bd6a4361a6d555b4f3c3bb4a4c437e6)
  - [ ] [CVE-2024-36041：KDE Plasma 漏洞导致未经授权的系统访问](https://mp.weixin.qq.com/s?__biz=MzkzNDIzNDUxOQ==&mid=2247486562&idx=2&sn=395a69ba9a967dc8e7db89b1097f37f0)
  - [ ] [GootLoader 恶意软件不断演变，仍通过 SEO 投毒造成严重破坏](https://mp.weixin.qq.com/s?__biz=MzkzNDIzNDUxOQ==&mid=2247486562&idx=3&sn=b1d260e347fc3eecfb0d307c6e40ad7d)
  - [ ] [配置错误的 Jenkins 服务器成为加密劫持攻击的目标](https://mp.weixin.qq.com/s?__biz=MzkzNDIzNDUxOQ==&mid=2247486562&idx=4&sn=7def818ef6c1732e85a5d85b9b6bf2da)
  - [ ] [拜登政府出手封杀卡巴斯基，国家安全面临新挑战](https://mp.weixin.qq.com/s?__biz=Mzg3OTYxODQxNg==&mid=2247484586&idx=1&sn=2df8a1937e66a827b291035f1de4e2c3)
  - [ ] [优秀文章分享：利用kerberos的各种特性进行权限维持，文章共三部分从各个方面介绍了如重置krbtgt后的权限维持手法](https://mp.weixin.qq.com/s?__biz=MzU0MjUxNjgyOQ==&mid=2247492203&idx=1&sn=2221c1399e7d3e81a382e9de4c8f54cc)
  - [ ] [安全技术测试-第1期](https://mp.weixin.qq.com/s?__biz=MzkzNDQ0MDcxMw==&mid=2247485479&idx=1&sn=6a34fb33bd631f4021285bfb40d6ee7a)
  - [ ] [无问社区 | 特色功能上新...](https://mp.weixin.qq.com/s?__biz=MzkzNDQ0MDcxMw==&mid=2247485479&idx=2&sn=7b89354ee6dc39b2ed279a7397c23b15)
  - [ ] [中国工业互联网研究院党委书记田川：持续推进数字化转型 促进中小企业高质量发展](https://mp.weixin.qq.com/s?__biz=MzkyMDMwNTkwNg==&mid=2247487146&idx=1&sn=2f6e9e2ac52f8bd1acfdbc26930ca6d3)
  - [ ] [网络安全必修课：如何应对SQL注入攻击？](https://mp.weixin.qq.com/s?__biz=MzI5MjY4MTMyMQ==&mid=2247484596&idx=1&sn=7cd7087579444bc3173281fc3764a0c2)
  - [ ] [红队在 Azure 上使用Mythic C2语音钓鱼](https://mp.weixin.qq.com/s?__biz=MzkzNjY3MTc1MA==&mid=2247484202&idx=1&sn=7414fc3014919c523e5115e7c0e5a390)
  - [ ] [2024 年 H1 TOP50网络安全统计数据（有关勒索软件、网络钓鱼、行业趋势等的重要见解）](https://mp.weixin.qq.com/s?__biz=Mzg4MzA4NTM0OA==&mid=2247490804&idx=1&sn=74ed227948eb38fad08cee47655c72cd)
  - [ ] [记一次护网通过外网弱口令一路到内网](https://mp.weixin.qq.com/s?__biz=MzUyODkwNDIyMg==&mid=2247541646&idx=1&sn=db11ea84c2fbdd00ea960b0364f7b3ab)
- Security Boulevard
  - [ ] [Paperclip Maximizers, Artificial Intelligence and Natural Stupidity](https://securityboulevard.com/2024/07/paperclip-maximizers-artificial-intelligence-and-natural-stupidity/)
  - [ ] [USENIX Security ’23 – Notice the Imposter! A Study on User Tag Spoofing Attack in Mobile Apps](https://securityboulevard.com/2024/07/usenix-security-23-notice-the-imposter-a-study-on-user-tag-spoofing-attack-in-mobile-apps/)
  - [ ] [Applying Bloch’s Philosophy to Cyber Security](https://securityboulevard.com/2024/07/applying-blochs-philosophy-to-cyber-security/)
- unSafe.sh - 不安全
  - [ ] [Shopify denies it was hacked, links stolen data to third-party app](https://buaq.net/go-249208.html)
  - [ ] [Europol says Home Routing mobile encryption feature aids criminals](https://buaq.net/go-249209.html)
  - [ ] [科学家研制出第一种无阳极钠固态电池](https://buaq.net/go-249220.html)
  - [ ] [USENIX Security ’23 – Notice the Imposter! A Study on User Tag Spoofing Attack in Mobile Apps](https://buaq.net/go-249212.html)
  - [ ] [中储粮调查油罐混用事件](https://buaq.net/go-249221.html)
  - [ ] [Security Affairs Malware Newsletter – Round 1](https://buaq.net/go-249210.html)
  - [ ] [SecMet#5期  智能代码审计：机遇、挑战与解决方案](https://buaq.net/go-249217.html)
  - [ ] [Refactoring 014 - How to Remove IF](https://buaq.net/go-249223.html)
  - [ ] [How Artificial Intelligence Can Make Our Smart Homes, Smarter](https://buaq.net/go-249224.html)
  - [ ] [Recommendations for Verifying HDR Subjective Testing Workflows: Abstract and Introduction](https://buaq.net/go-249225.html)
  - [ ] [Recommendations for Verifying HDR Subjective Testing Workflows: HDR Standards](https://buaq.net/go-249228.html)
  - [ ] [Recommendations for Verifying HDR Subjective Testing Workflows: Conclusion](https://buaq.net/go-249227.html)
  - [ ] [Recommendations for Verifying HDR Subjective Testing Workflows: HDR Subjective Testing Workflow](https://buaq.net/go-249226.html)
- MaskRay
  - [ ] [Linker compatibility and the "User-Agent" problem](https://maskray.me/blog/2024-07-07-linker-compatibility-and-the-user-agent-problem)
- HackerNoon
  - [ ] [Does Generative AI Violate the Rights of Authors and Artists?](https://hackernoon.com/does-generative-ai-violate-the-rights-of-authors-and-artists?source=rss)
  - [ ] [The Noonification: BEP 341: Consecutive Block Production (7/7/2024)](https://hackernoon.com/7-7-2024-noonification?source=rss)
  - [ ] [Refactoring 014 - How to Remove IF](https://hackernoon.com/refactoring-014-how-to-remove-if?source=rss)
  - [ ] [How Artificial Intelligence Can Make Our Smart Homes, Smarter](https://hackernoon.com/how-artificial-intelligence-can-make-our-smart-homes-smarter?source=rss)
  - [ ] [Recommendations for Verifying HDR Subjective Testing Workflows: Abstract and Introduction](https://hackernoon.com/recommendations-for-verifying-hdr-subjective-testing-workflows-abstract-and-introduction?source=rss)
  - [ ] [Recommendations for Verifying HDR Subjective Testing Workflows: HDR Subjective Testing Workflow](https://hackernoon.com/recommendations-for-verifying-hdr-subjective-testing-workflows-hdr-subjective-testing-workflow?source=rss)
  - [ ] [Recommendations for Verifying HDR Subjective Testing Workflows: Conclusion](https://hackernoon.com/recommendations-for-verifying-hdr-subjective-testing-workflows-conclusion?source=rss)
  - [ ] [Recommendations for Verifying HDR Subjective Testing Workflows: HDR Standards](https://hackernoon.com/recommendations-for-verifying-hdr-subjective-testing-workflows-hdr-standards?source=rss)
- Security Blog | Praetorian
  - [ ] [Continuous Threat Exposure Management for Google Cloud](https://www.praetorian.com/blog/continuous-threat-exposure-management-for-google-cloud/)
- 奇客Solidot–传递最新科技情报
  - [ ] [科学家研制出第一种无阳极钠固态电池](https://www.solidot.org/story?sid=78626)
  - [ ] [中储粮调查油罐混用事件](https://www.solidot.org/story?sid=78625)
- 看雪学苑
  - [ ] [『SDC 2024』创新议题等你来投！早鸟票抢购中](https://mp.weixin.qq.com/s?__biz=MjM5NTc2MDYxMw==&mid=2458562488&idx=1&sn=e5cc0a0dd4dff941866c4e034a783a13&chksm=b18d9f3286fa162426bfc9d6f32503f29bbad4094b14333294d27969bbbb76ee41f73f57d2cd&scene=58&subscene=0#rd)
  - [ ] [VMP源码分析：反调试与绕过方法](https://mp.weixin.qq.com/s?__biz=MjM5NTc2MDYxMw==&mid=2458562488&idx=2&sn=fe5bd1498948137775db5f454bd5a6a2&chksm=b18d9f3286fa162491072b9cd141784c1a60b2b00fd8203f865c51ef753e3f45573a78810949&scene=58&subscene=0#rd)
- 天御攻防实验室
  - [ ] [终端入侵对抗：Sysmon还EDR？](https://mp.weixin.qq.com/s?__biz=MzU0MzgyMzM2Nw==&mid=2247485883&idx=1&sn=6ca8d0bc5a6abd6d31f5575446292b69&chksm=fb04cad3cc7343c5434958338ac2a21a7b0eccc078f17b4c061ac0840e3fbfc3a04f22ba66e7&scene=58&subscene=0#rd)
- dotNet安全矩阵
  - [ ] [.NET 通过Windows系统计划任务维权](https://mp.weixin.qq.com/s?__biz=MzUyOTc3NTQ5MA==&mid=2247493151&idx=1&sn=5938d4294d0297adb511aa89cebd47a8&chksm=fa5948f2cd2ec1e42feb7c14167dbbe475596f2af7ed9744517b65f418189fd1999a81cb9a9f&scene=58&subscene=0#rd)
  - [ ] [两个国内最专业的.NET安全知识库](https://mp.weixin.qq.com/s?__biz=MzUyOTc3NTQ5MA==&mid=2247493151&idx=2&sn=a0f98c8e0983bb02ec2f758001e20933&chksm=fa5948f2cd2ec1e464d9c1cf04bfb3da56612b43518029939944f8844f1fabbe67d81e7ff543&scene=58&subscene=0#rd)
- 青衣十三楼飞花堂
  - [ ] [王芳回忆录](https://mp.weixin.qq.com/s?__biz=MzUzMjQyMDE3Ng==&mid=2247487495&idx=1&sn=7d8daafe0c9b1195c4cd23fb4b40de1c&chksm=fab2d338cdc55a2e3bdb4b7531f248e43ed9142410e5a649b755c60a36254066330d5fe8650d&scene=58&subscene=0#rd)
- 安全学术圈
  - [ ] [SecMet#5期  智能代码审计：机遇、挑战与解决方案](https://mp.weixin.qq.com/s?__biz=MzU5MTM5MTQ2MA==&mid=2247491039&idx=1&sn=1c7aad358d4c0cc2f595b0beafc92b1b&chksm=fe2ee254c9596b42ffcbfeb003fbff602f17f23303f3907cb1c8bd9cdf0fe0a0035459e071c2&scene=58&subscene=0#rd)
- 丁爸 情报分析师的工具箱
  - [ ] [【通知】第十期全国开源能力提升培训班—开源尖兵实战训练营7.23-7.28天津开训](https://mp.weixin.qq.com/s?__biz=MzI2MTE0NTE3Mw==&mid=2651144812&idx=1&sn=f1638fba432ed3bbd2b27a0689e489e9&chksm=f1af3556c6d8bc4076e83eb77aa0d9d72c7a792c5955b7cfa5e9a014f3f8d8ace08abf764478&scene=58&subscene=0#rd)
  - [ ] [【AI速读】兰德建议：加强生物武器蓄意使用调查的能力](https://mp.weixin.qq.com/s?__biz=MzI2MTE0NTE3Mw==&mid=2651144812&idx=2&sn=b17600d6a1c37039986d165747f1ae46&chksm=f1af3556c6d8bc4077a9d2fdb382bdfb806011022a0be24555d61de5eb7270b6ce85f93d9b6e&scene=58&subscene=0#rd)
- 情报分析师
  - [ ] [用于分析卫星图像的九种开源工具](https://mp.weixin.qq.com/s?__biz=MzA3Mjc1MTkwOA==&mid=2650552003&idx=1&sn=f65ee38ef01354b24caf6488d65c6a01&chksm=87111888b066919e09581a78df2d2d78ac0390d3ad392aaf99deae4eb140df117e732d110be0&scene=58&subscene=0#rd)
  - [ ] [《每日开源》获取每日开源信息！](https://mp.weixin.qq.com/s?__biz=MzA3Mjc1MTkwOA==&mid=2650552003&idx=2&sn=6291faffb2575125a5c6e2674e16a068&chksm=87111888b066919e097a4fb2a9a81ec6e9fa0263fdac17b79fab02640a307af8903fcdd99796&scene=58&subscene=0#rd)
- 极客公园
  - [ ] [马斯克：8月初开始第五次星舰试飞：上海发布开放签署式人形机器人治理规则文件；米哈游《绝区零》下载量破5000万 | 极客早知道](https://mp.weixin.qq.com/s?__biz=MTMwNDMwODQ0MQ==&mid=2653046916&idx=1&sn=bf5838112e3653b93ad0541c4b67c0ce&chksm=7e5735324920bc2457a05a6abe6c64004f533f5f2dae63984d2c0e99f83ffaa6dc3517cd7353&scene=58&subscene=0#rd)
- TecHug
  - [ ] [【外评】代码审查确实能发现漏洞](https://www.techug.com/post/code-reviews-do-find-bugs/)
- 极道
  - [ ] [在 JDBC 中获取插入 ID](https://www.jdon.com/74482.html)
  - [ ] [Spring Boot事务发件箱模式](https://www.jdon.com/74481.html)
  - [ ] [Java中命名执行器服务线程和线程池](https://www.jdon.com/74480.html)
  - [ ] [三则大模型使用提示技巧](https://www.jdon.com/74479.html)
- bang’s blog
  - [ ] [Transformer 里的 Q K V 是什么](http://blog.cnbang.net/tech/3934/)
- Nicksxs's Blog
  - [ ] [聊一下 Spring 的 SmartLifecycle 使用](https://nicksxs.me/2024/07/07/%E8%81%8A%E4%B8%80%E4%B8%8B-Spring-%E7%9A%84-SmarLifecycle-%E4%BD%BF%E7%94%A8/)
- 知足常乐-水星投资理财的基本意念
  - [ ] [享受當下的時間段](http://mercurychong.blogspot.com/2024/07/blog-post_6.html)
- Jason
  - [ ] [0707 - 服务意识](https://atjason.com/daily/2024-07-07.html)
- 白宦成
  - [ ] [公司的期权该卖么？](https://www.ixiqin.com/2024/07/08/should-the-companys-options-be-sold/)
- Yiran's Blog
  - [ ] [Weekly Issue-BlueBuild 项目](https://zdyxry.github.io/2024/07/07/Weekly-Issue-BlueBuild-%E9%A1%B9%E7%9B%AE/)
- 维基萌
  - [ ] [今天逛了逛二手商店的《点兔》区，发现纱路复制原画要33000日元（约1492元人民币），隔壁全员大集...](https://www.wikimoe.com/post/ryx7rp5d)
  - [ ] [久违的女仆咖啡，好像现在在和一款手游联动。](https://www.wikimoe.com/post/bk1iq94c)
- 卢昌海个人主页
  - [ ] [微言小义 (2024.06)](https://www.changhai.org/articles/miscellaneous/blog/202406.php)
- 渚碧
  - [ ] [当慢下来的时候](https://jubeny.com/2024/07/when-i-slow-down/)
- 重归混沌的BLOG
  - [ ] [谈谈游戏服务器的自动化测试](https://blog.gotocoding.com/archives/1898?utm_source=rss&utm_medium=rss&utm_campaign=%25e8%25b0%2588%25e8%25b0%2588%25e6%25b8%25b8%25e6%2588%258f%25e6%259c%258d%25e5%258a%25a1%25e5%2599%25a8%25e7%259a%2584%25e8%2587%25aa%25e5%258a%25a8%25e5%258c%2596%25e6%25b5%258b%25e8%25af%2595)
- 葉開三言兩語
  - [ ] ["九块九包邮耳机的“翻车”之旅"叶开新动态](https://qq.md/post/743)
- 木鸟杂记
  - [ ] [使用 ray.data 进行大规模数据处理（二）：全局视角](https://www.qtmuniao.com/2024/07/07/ray-data-2/)
- Allen Hua 的网络博客
  - [ ] [入门三脚架推荐｜云腾VCT-668配合索尼A7C2+FE 35mm F1.8 第一次夜景出片](https://hellodk.cn/post/1178)
- 空城记
  - [ ] [花は香り、月は曇り](https://shinekid.com/2024/07/flowers-are-fragrant-and-moon-is-dim/)
- 小球飞鱼
  - [ ] [小暑 | 在热浪中心呼唤：大——薯——](/weekly/2024/jun.17-jul.07/)
- Lei Mao's Log Book
  - [ ] [UPS 电源的重要性](https://leimao.github.io/essay/UPS%E7%94%B5%E6%BA%90%E7%9A%84%E9%87%8D%E8%A6%81%E6%80%A7/)
